name: Build EXE 64 and 32 bits

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-64bit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 64-bit
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE 64-bit
        run: pyinstaller --onefile --windowed --icon=assets/icono.ico --add-data "assets;assets" --add-data "db;db" --add-data "gui;gui" main.py
      
      - name: Check EXE architecture
        shell: powershell
        run: |
          $bytes = Get-Content -Path dist/main.exe -Encoding Byte -TotalCount 1024
          $peOffset = [BitConverter]::ToInt32($bytes[60..63],0)
          $machine = [BitConverter]::ToUInt16($bytes[$peOffset+4..$peOffset+5],0)
          switch ($machine) {
            0x014c { "Arquitectura detectada: 32-bit (x86)" }
            0x8664 { "Arquitectura detectada: 64-bit (x64)" }
            default { "Arquitectura desconocida: $machine" }
          }


      - name: Upload 64bit EXE
        uses: actions/upload-artifact@v4
        with:
          name: PyKey-64bit
          path: dist/main.exe

  build-32bit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 32-bit
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.11.5/python-3.11.5.exe -OutFile python32.exe
          Start-Process -Wait -FilePath python32.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1 Include_pip=1'
      - name: Setup Python 32-bit
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build EXE 32-bit
        run: |
          pyinstaller --onefile --windowed --icon=assets/icono.ico --add-data "assets;assets" --add-data "db;db" --add-data "gui;gui" main.py

      - name: Check EXE architecture
        shell: powershell
        run: |
          $bytes = Get-Content -Path dist/main.exe -Encoding Byte -TotalCount 1024
          $peOffset = [BitConverter]::ToInt32($bytes[60..63],0)
          $machine = [BitConverter]::ToUInt16($bytes[$peOffset+4..$peOffset+5],0)
          switch ($machine) {
            0x014c { "Arquitectura detectada: 32-bit (x86)" }
            0x8664 { "Arquitectura detectada: 64-bit (x64)" }
            default { "Arquitectura desconocida: $machine" }
          }



      - name: Upload 32bit EXE
        uses: actions/upload-artifact@v4
        with:
          name: PyKey-32bit
          path: dist/main.exe
  
